### ISSUE TITLE
Unable to find openssl?

### ISSUE THREAD

**Issue by latetedemelon** [PhrantiK/letsdnsocloud#5]
Platform: Raspberry Pi 3+ 
OS: Raspbian Buster
Hassio:  0.103.6

Vanilla install from scratch (including OS).  Installed this plugin as the first one once the system was up and running (added a few out of the box integrations first).  Got the following error:

```
A record created for sub.mydomain.xxx at xxx.xxx.xxx.xxx
# INFO: Using main config file /data/workdir/config
ERROR: This script requires an openssl binary.
```

Openssl binary is present on both the docker container and the base system so I'm not sure why the addon isn't' able to find it.  Any help would be amazing.

**Comment by niXta1** [comment]
Same on a NUC.

**Comment by Colgaton** [comment]
Just sent a pull request to fix this. Works for me when running it in Ubuntu and hassio.

**Comment by latetedemelon** [comment]
#6 Tested this my applying manually to my system; confirmed this fixed the issue.

Thanks a bunch @Colgaton

**Comment by niXta1** [comment]
Same here, forked and modified the repo address, added niXta1/hassio-addons to hassio and it works. 👍🏻

**Comment by boojew** [comment]
EDIT: sorry- misread. Ignore me.

**Comment by PhrantiK** [comment]
Merged - thanks @Colgaton
