### ISSUE TITLE
Feature request: config switch for proxy

### ISSUE THREAD

**Issue by jamesgreeley** [PhrantiK/letsdnsocloud#8]
Could you please add config option to whether to have cloud flare set the A record to proxied or DNS only?

**Comment by alsolh** [comment]
thanks for your awesome hassio addon, can you please approve this pull request to add the configuration parameter for proxied as requested in this post?

https://github.com/PhrantiK/hassio-addons/pull/11

**Comment by PhrantiK** [comment]
Apologies for the super slow response! @alsolh thanks for making this happen.
