### ISSUE TITLE
http and https

### ISSUE THREAD

**Issue by johan149** [PhrantiK/letsdnsocloud#9]
there is any way we can have both http and https access? google home cannot work through https so I'm trying to serve the mp3 files through http, I would love to have that option I've been using it for 1 year already without any issues. Thank You!

**Comment by PhrantiK** [comment]
Sorry for the late response. 

You'll need a reverse proxy in addition to this add-on: https://community.home-assistant.io/t/home-assistant-internal-url-without-https/238200
